apiVersion: v2
name: heart-disease-api
description: A Helm chart for the Heart Disease Prediction MLOps application (Backend API + Frontend + Monitoring)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - mlops
  - machine-learning
  - heart-disease
  - fastapi
  - django
maintainers:
  - name: 2024ab05112
