apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heart-disease-api.fullname" . }}-backend
  labels:
    app: {{ include "heart-disease-api.name" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "heart-disease-api.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "heart-disease-api.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
