apiVersion: v1
kind: Service
metadata:
  name: heart-disease-api-service
  labels:
    app: {{ include "heart-disease-api.name" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "heart-disease-api.name" . }}-backend
