apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heart-disease-api.fullname" . }}
  labels:
    app: {{ include "heart-disease-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "heart-disease-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "heart-disease-api.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
