apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heart-disease-api.fullname" . }}-frontend
  labels:
    app: {{ include "heart-disease-api.name" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "heart-disease-api.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "heart-disease-api.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: BACKEND_API_URL
              value: "http://heart-disease-api-service:80/predict"
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
